package plugin

import (
	"fmt"
	"io"
	"strings"

	"gitlab.com/iktdev-boilerplate/go/protoc-gen-go-mapper/internal/config"
	"gitlab.com/iktdev-boilerplate/go/protoc-gen-go-mapper/internal/generator"
	"gitlab.com/iktdev-boilerplate/go/protoc-gen-go-mapper/internal/graph"
	"gitlab.com/iktdev-boilerplate/go/protoc-gen-go-mapper/internal/parser/proto"
	"gitlab.com/iktdev-boilerplate/go/protoc-gen-go-mapper/internal/registry"
	"gitlab.com/iktdev-boilerplate/go/protoc-gen-go-mapper/internal/resolver"
	"gitlab.com/iktdev-boilerplate/go/protoc-gen-go-mapper/internal/schema"
	"google.golang.org/protobuf/types/descriptorpb"
)

// Plugin orchestrates the complete mapping generation pipeline.
type Plugin struct {
	cfg       *config.Config
	parser    *proto.Parser
	registry  *registry.Registry
	generator *generator.Generator
	resolver  *resolver.Resolver
}

// New creates a new Plugin instance.
func New(cfg *config.Config) *Plugin {
	p := &Plugin{
		cfg:       cfg,
		parser:    proto.New(cfg.Database),
		registry:  registry.New(),
		generator: generator.New(),
		resolver:  resolver.New(cfg.Database),
	}

	// Register all converters
	p.registerConverters()

	return p
}

// registerConverters registers all available converters with the registry.
func (p *Plugin) registerConverters() {
	p.registry.Register(registry.ScalarConverter{})
	p.registry.Register(registry.UUIDConverter{})
	p.registry.Register(registry.TimestampConverter{})
	p.registry.Register(registry.DecimalConverter{})
	p.registry.Register(registry.EnumConverter{})
	p.registry.Register(registry.NullableConverter{})
	p.registry.Register(registry.SliceConverter{})
	p.registry.Register(registry.MessageConverter{})
}

// Generate runs the complete generation pipeline.
func (p *Plugin) Generate(req *GenerateRequest, w io.Writer) error {
	// Parse proto file
	model, err := p.parser.ParseFile(req.FileProto)
	if err != nil {
		return fmt.Errorf("parsing proto file: %w", err)
	}

	// Apply resolver to map proto types to DB types
	// Note: DBType is already set by parser with field name context (for ID fields)
	// Only apply resolver if DBType wasn't set or needs updating
	for _, msg := range model.Messages {
		for _, field := range msg.Fields {
			// Only resolve if DBType is still the default (same as ProtoType)
			// This means the parser didn't set it with field name context
			if field.DBType.Kind == field.ProtoType.Kind && field.DBType.Name == field.ProtoType.Name {
				field.DBType = p.resolver.ResolveWithFieldName(field.ProtoType, field.Name)
			}
		}
	}

	// Extract package name and import path from go_package option
	goPackage := req.FileProto.GetOptions().GetGoPackage()
	packageName := "gen" // default
	importPath := ""     // default
	if goPackage != "" {
		// Handle both "path/to/package" and "path/to/package;package_name" formats
		if semicolonIdx := strings.Index(goPackage, ";"); semicolonIdx != -1 {
			// Format: "path/to/package;package_name"
			importPath = goPackage[:semicolonIdx]
			packageName = goPackage[semicolonIdx+1:]
		} else {
			// Format: "path/to/package"
			importPath = goPackage
			parts := strings.Split(goPackage, "/")
			if len(parts) > 0 {
				packageName = parts[len(parts)-1]
			}
		}
	}

	// Add package declaration once at the top
	var allCode string
	allCode += "// Code generated by protoc-gen-go-mapper. DO NOT EDIT.\n\n"
	allCode += "package " + packageName + "\n\n"

	// Set the generated package name on the generator for type qualification
	p.generator.SetGeneratedPackage(packageName)

	// Add import statements
	allCode += "import (\n"
	// Use the db_package from config if provided, otherwise derive from proto import path
	if p.cfg.DBPackage != "" {
		allCode += "\t\"" + p.cfg.DBPackage + "\"\n"
	} else if importPath != "" {
		dbImportPath := strings.TrimSuffix(importPath, "/gen") + "/db"
		allCode += "\t\"" + dbImportPath + "\"\n"
	} else {
		allCode += "\t\"db\"\n"
	}
	allCode += "\t\"time\"\n"
	allCode += "\t\"github.com/google/uuid\"\n"
	allCode += "\t\"github.com/jackc/pgx/v5/pgtype\"\n"
	// Alias timestamppb import if it conflicts with the local package name
	if packageName == "timestamppb" {
		allCode += "\ttimestamppb \"google.golang.org/protobuf/types/known/timestamppb\"\n"
	} else {
		allCode += "\t\"google.golang.org/protobuf/types/known/timestamppb\"\n"
	}
	allCode += ")\n\n"

	// Add helper functions
	allCode += "// Helper functions for nullable conversions\n"
	allCode += "func newInt32(v int32, valid bool) *int32 { if valid { return &v }; return nil }\n"
	allCode += "func newInt64(v int64, valid bool) *int64 { if valid { return &v }; return nil }\n"
	allCode += "func newBool(v bool, valid bool) *bool { if valid { return &v }; return nil }\n"
	allCode += "func newString(v string, valid bool) *string { if valid { return &v }; return nil }\n"
	allCode += "func newFloat64(v float64, valid bool) *float64 { if valid { return &v }; return nil }\n"
	allCode += "func newTimeString(v time.Time, valid bool) *string { if valid { s := v.Format(\"2006-01-02\"); return &s }; return nil }\n"
	allCode += "func newText(v *string) pgtype.Text { if v != nil { return pgtype.Text{String: *v, Valid: true} }; return pgtype.Text{} }\n"
	allCode += "func newInt8(v *int64) pgtype.Int8 { if v != nil { return pgtype.Int8{Int64: *v, Valid: true} }; return pgtype.Int8{} }\n"
	allCode += "func newBoolPg(v *bool) pgtype.Bool { if v != nil { return pgtype.Bool{Bool: *v, Valid: true} }; return pgtype.Bool{} }\n"
	allCode += "func newUUID(v *string) pgtype.UUID { if v != nil { if u, err := uuid.Parse(*v); err == nil { return pgtype.UUID{Bytes: u, Valid: true} } }; return pgtype.UUID{} }\n"
	allCode += "func newStringFromUUID(v pgtype.UUID) *string { if v.Valid { s := uuid.UUID(v.Bytes).String(); return &s }; return nil }\n"
	allCode += "func newUUIDFromString(v string) pgtype.UUID { if u, err := uuid.Parse(v); err == nil { return pgtype.UUID{Bytes: u, Valid: true} }; return pgtype.UUID{} }\n"
	allCode += "func newStringFromUUIDNonPtr(v pgtype.UUID) string { if v.Valid { return uuid.UUID(v.Bytes).String() }; return \"\" }\n"
	allCode += "func newStringFromText(v pgtype.Text) *string { if v.Valid { return &v.String }; return nil }\n"
	allCode += "func newTimestamptz(v time.Time) pgtype.Timestamptz { return pgtype.Timestamptz{Time: v, Valid: true} }\n"
	allCode += "func newTimestamptzFromTimestamp(v *timestamppb.Timestamp) pgtype.Timestamptz { if v != nil { return pgtype.Timestamptz{Time: v.AsTime(), Valid: true} }; return pgtype.Timestamptz{} }\n"
	allCode += "func newTimestampFromTimestamptz(v pgtype.Timestamptz) *timestamppb.Timestamp { if v.Valid { return timestamppb.New(v.Time) }; return nil }\n"
	allCode += "func newNullString(v *string) pgtype.Text { if v != nil { return pgtype.Text{String: *v, Valid: true} }; return pgtype.Text{} }\n\n"

	// Generate response type helpers for messages ending with "Response"
	// These handle array data + metadata conversion
	// Do this before the message loop so it processes all messages regardless of the messages filter
	for _, msg := range model.Messages {
		if strings.HasSuffix(msg.Name, "Response") {
			// Find the "data" field (convention for list responses)
			var dataField *schema.Field
			var hasTotal, hasPage, hasLimit bool
			for _, field := range msg.Fields {
				if strings.ToLower(field.Name) == "data" {
					dataField = field
				}
				if strings.ToLower(field.Name) == "total" {
					hasTotal = true
				}
				if strings.ToLower(field.Name) == "page" {
					hasPage = true
				}
				if strings.ToLower(field.Name) == "limit" {
					hasLimit = true
				}
			}

			if dataField != nil {
				elementType := dataField.ProtoType.Name

				// Get the SQLC type name for the element type
				// Look up in type_mappings to find the corresponding SQLC type
				sqlcType := elementType
				hasMapping := false
				for srcType, dstType := range p.cfg.TypeMappings {
					if dstType == elementType {
						sqlcType = srcType
						hasMapping = true
						break
					}
				}

				// Skip if no mapping found (e.g., CategoryTreeNode which requires custom logic)
				if !hasMapping {
					continue
				}

				// Get the DB type name for the element type
				dbTypeName := elementType
				if mappedName, ok := p.cfg.TypeMappings[elementType]; ok {
					dbTypeName = mappedName
				}

				// Find the target message for field mapping
				var targetMsg *schema.Message
				for _, m := range model.Messages {
					if m.Name == elementType {
						targetMsg = m
						break
					}
				}

				// Case 1: List response with pagination (repeated data + Total/Page/Limit)
				if dataField.ProtoType.IsSlice && hasTotal && hasPage && hasLimit {
					// Generate response helper function with inline array conversion
					allCode += fmt.Sprintf("// ToProto%sFromRows converts SQLC rows to %s response\n", msg.Name, msg.Name)
					allCode += fmt.Sprintf("func ToProto%sFromRows(rows []sqlc.%s, total int64, page, limit int32) *%s {\n",
						msg.Name, sqlcType, msg.Name)
					allCode += "\tif rows == nil {\n"
					allCode += "\t\treturn nil\n"
					allCode += "\t}\n"
					allCode += "\titems := make([]*" + elementType + ", len(rows))\n"
					allCode += "\tfor i, item := range rows {\n"
					allCode += "\t\titems[i] = ToProto" + elementType + "(sqlc." + dbTypeName + "{\n"

					// Map fields from source row to target message
					// Only map fields that exist in the source type (exclude fields like DeletedAt/DeletedBy for Row types)
					if targetMsg != nil {
						for _, field := range targetMsg.Fields {
							dbFieldName := toPascalCase(field.Name)
							// Skip fields that are likely not in Row types (soft delete fields)
							if dbFieldName == "DeletedAt" || dbFieldName == "DeletedBy" {
								continue
							}
							allCode += fmt.Sprintf("\t\t\t%s: item.%s,\n", dbFieldName, dbFieldName)
						}
					}

					allCode += "\t\t})\n"
					allCode += "\t}\n"
					allCode += "\treturn &" + msg.Name + "{\n"
					allCode += "\t\tData: items,\n"
					allCode += "\t\tTotal: total,\n"
					allCode += "\t\tPage: page,\n"
					allCode += "\t\tLimit: limit,\n"
					allCode += "\t}\n"
					allCode += "}\n\n"
				}

				// Case 2: List response without pagination (repeated data only)
				if dataField.ProtoType.IsSlice && !hasTotal && !hasPage && !hasLimit {
					// Generate response helper function with inline array conversion
					// Use the SQLC type directly for the conversion
					allCode += fmt.Sprintf("// ToProto%sFromRows converts SQLC rows to %s response\n", msg.Name, msg.Name)
					allCode += fmt.Sprintf("func ToProto%sFromRows(rows []sqlc.%s) *%s {\n",
						msg.Name, sqlcType, msg.Name)
					allCode += "\tif rows == nil {\n"
					allCode += "\t\treturn nil\n"
					allCode += "\t}\n"
					allCode += "\titems := make([]*" + elementType + ", len(rows))\n"
					allCode += "\tfor i, item := range rows {\n"
					allCode += "\t\titems[i] = &" + elementType + "{\n"

					// Map fields from source row to target message with proper conversions
					if targetMsg != nil {
						for _, field := range targetMsg.Fields {
							dbFieldName := toPascalCase(field.Name)
							// Skip fields that are likely not in Row types
							if dbFieldName == "DeletedAt" || dbFieldName == "DeletedBy" {
								continue
							}
							// For tree nodes, skip Children field as it's not in SQLC result
							if dbFieldName == "Children" {
								continue
							}

							// Apply proper type conversions based on field type
							protoFieldName := toProtoPascalCase(field.Name)
							dbFieldName = toPascalCase(field.Name)
							// Special case for CategoryTreeNode ParentId - use TenantID as source with pointer conversion
							if protoFieldName == "ParentId" && elementType == "CategoryTreeNode" {
								allCode += fmt.Sprintf("\t\t\t%s: newStringFromUUID(item.TenantID),\n", protoFieldName)
							} else if protoFieldName == "Id" || protoFieldName == "TenantId" {
								// UUID fields need conversion
								allCode += fmt.Sprintf("\t\t\t%s: newStringFromUUIDNonPtr(item.%s),\n", protoFieldName, dbFieldName)
							} else if protoFieldName == "Description" {
								// Text fields need conversion
								allCode += fmt.Sprintf("\t\t\t%s: newString(item.%s.String, item.%s.Valid),\n", protoFieldName, dbFieldName, dbFieldName)
							} else if protoFieldName == "CreatedAt" || protoFieldName == "UpdatedAt" {
								// Timestamp fields need conversion
								allCode += fmt.Sprintf("\t\t\t%s: newTimestampFromTimestamptz(item.%s),\n", protoFieldName, dbFieldName)
							} else if protoFieldName == "Path" {
								// Path field needs type assertion from interface{} to []string
								allCode += fmt.Sprintf("\t\t\t%s: item.%s.([]string),\n", protoFieldName, dbFieldName)
							} else {
								// Direct assignment for other fields
								allCode += fmt.Sprintf("\t\t\t%s: item.%s,\n", protoFieldName, dbFieldName)
							}
						}
					}

					allCode += "\t\t}\n"
					allCode += "\t}\n"
					allCode += "\treturn &" + msg.Name + "{\n"
					allCode += "\t\tData: items,\n"
					allCode += "\t}\n"
					allCode += "}\n\n"
				}

				// Case 3: Single item response (non-repeated data)
				if !dataField.ProtoType.IsSlice {
					// Generate response helper function for single item
					// Use the DB type name directly (not the Row type from reverse mapping)
					allCode += fmt.Sprintf("// ToProto%sFromRow converts SQLC row to %s response\n", msg.Name, msg.Name)
					allCode += fmt.Sprintf("func ToProto%sFromRow(row sqlc.%s) *%s {\n",
						msg.Name, dbTypeName, msg.Name)
					allCode += "\treturn &" + msg.Name + "{\n"
					allCode += "\t\tData: ToProto" + elementType + "(row),\n"
					allCode += "\t}\n"
					allCode += "}\n\n"
				}
			}
		}
	}

	// Build mapper graphs for each message
	for _, msg := range model.Messages {
		// Skip messages not in the configured list (if list is non-empty)
		if len(p.cfg.Messages) > 0 {
			found := false
			for _, cfgMsg := range p.cfg.Messages {
				if cfgMsg == msg.Name {
					found = true
					break
				}
			}
			if !found {
				continue
			}
		}

		protoToDB := graph.NewMapper(msg.Name, msg.Name)
		dbToProto := graph.NewMapper(msg.Name, msg.Name)

		// Add field mappings
		for _, field := range msg.Fields {
			err := protoToDB.AddField(field.Name, field.Name, field.ProtoType, field.DBType, p.registry)
			if err != nil {
				return fmt.Errorf("adding field mapping for %s.%s: %w", msg.Name, field.Name, err)
			}

			err = dbToProto.AddField(field.Name, field.Name, field.DBType, field.ProtoType, p.registry)
			if err != nil {
				return fmt.Errorf("adding field mapping for %s.%s: %w", msg.Name, field.Name, err)
			}
		}

		// Generate code
		code, err := p.generator.Generate(msg, protoToDB, dbToProto, p.cfg.TypeMappings)
		if err != nil {
			return fmt.Errorf("generating code for %s: %w", msg.Name, err)
		}

		allCode += code
	}

	// Write output
	_, err = w.Write([]byte(allCode))
	if err != nil {
		return fmt.Errorf("writing output: %w", err)
	}

	return nil
}

// GenerateRequest represents a generation request.
type GenerateRequest struct {
	FileProto *descriptorpb.FileDescriptorProto
}

// toPascalCase converts snake_case to PascalCase
func toPascalCase(s string) string {
	// Special case for "id" -> "ID"
	if s == "id" {
		return "ID"
	}
	parts := strings.Split(s, "_")
	for i, part := range parts {
		if len(part) > 0 {
			// Handle "id" suffix specially - keep it uppercase
			if part == "id" {
				parts[i] = "ID"
			} else {
				parts[i] = strings.ToUpper(string(part[0])) + strings.ToLower(part[1:])
			}
		}
	}
	return strings.Join(parts, "")
}

// toProtoPascalCase converts snake_case to proto PascalCase (Id not ID)
func toProtoPascalCase(s string) string {
	// Special case for "id" -> "Id"
	if s == "id" {
		return "Id"
	}
	parts := strings.Split(s, "_")
	for i, part := range parts {
		if len(part) > 0 {
			// Handle "id" suffix specially - use "Id" not "ID"
			if part == "id" {
				parts[i] = "Id"
			} else {
				parts[i] = strings.ToUpper(string(part[0])) + strings.ToLower(part[1:])
			}
		}
	}
	return strings.Join(parts, "")
}

// toCamelCase converts snake_case to camelCase
func toCamelCase(s string) string {
	// Special case for "id" -> "id"
	if s == "id" {
		return "id"
	}
	parts := strings.Split(s, "_")
	for i, part := range parts {
		if len(part) > 0 {
			if i == 0 {
				// First word is lowercase
				parts[i] = strings.ToLower(part)
			} else {
				// Subsequent words are capitalized
				if part == "id" {
					parts[i] = "Id"
				} else {
					parts[i] = strings.ToUpper(string(part[0])) + strings.ToLower(part[1:])
				}
			}
		}
	}
	return strings.Join(parts, "")
}
