package plugin

import (
	"fmt"
	"io"
	"strings"

	"github.com/jwart212/protoc-gen-go-mapper/internal/config"
	"github.com/jwart212/protoc-gen-go-mapper/internal/generator"
	"github.com/jwart212/protoc-gen-go-mapper/internal/graph"
	"github.com/jwart212/protoc-gen-go-mapper/internal/handler"
	"github.com/jwart212/protoc-gen-go-mapper/internal/parser/proto"
	"github.com/jwart212/protoc-gen-go-mapper/internal/registry"
	"github.com/jwart212/protoc-gen-go-mapper/internal/resolver"
	"github.com/jwart212/protoc-gen-go-mapper/internal/schema"
	"google.golang.org/protobuf/types/descriptorpb"
)

// Plugin orchestrates the complete mapping generation pipeline.
type Plugin struct {
	cfg            *config.Config
	parser         *proto.Parser
	registry       *registry.Registry
	generator      *generator.Generator
	resolver       *resolver.Resolver
	handlerReg     *handler.HandlerRegistry
	typeHandlerReg *handler.HandlerRegistry
}

// New creates a new Plugin instance.
func New(cfg *config.Config) *Plugin {
	p := &Plugin{
		cfg:       cfg,
		parser:    proto.New(cfg.Database),
		registry:  registry.New(),
		generator: generator.New(),
		resolver:  resolver.New(cfg.Database),
	}

	// Register all converters
	p.registerConverters()

	// Load field handlers from configuration
	if len(cfg.FieldHandlers) > 0 {
		handlerReg, err := handler.LoadHandlers(cfg.FieldHandlers)
		if err != nil {
			// Log error but don't fail - we'll use default behavior
			fmt.Printf("Warning: failed to load field handlers: %v\n", err)
		} else {
			p.handlerReg = handlerReg
			p.generator.SetHandlerRegistry(handlerReg)
		}
	}

	// Load type conversion handlers from configuration
	if len(cfg.TypeConversions) > 0 {
		typeHandlerReg, err := handler.LoadTypeConversions(cfg.TypeConversions, cfg.TypeAliases)
		if err != nil {
			// Log error but don't fail - we'll use default behavior
			fmt.Printf("Warning: failed to load type conversion handlers: %v\n", err)
		} else {
			p.typeHandlerReg = typeHandlerReg
		}
	}

	return p
}

// registerConverters registers all available converters with the registry.
func (p *Plugin) registerConverters() {
	p.registry.Register(registry.ScalarConverter{})
	p.registry.Register(registry.UUIDConverter{})
	p.registry.Register(registry.TimestampConverter{})
	p.registry.Register(registry.DecimalConverter{})
	p.registry.Register(registry.EnumConverter{})
	p.registry.Register(registry.NullableConverter{})
	p.registry.Register(registry.SliceConverter{})
	p.registry.Register(registry.MessageConverter{})
}

// Generate runs the complete generation pipeline.
func (p *Plugin) Generate(req *GenerateRequest, w io.Writer) error {
	// Parse proto file
	model, err := p.parser.ParseFile(req.FileProto)
	if err != nil {
		return fmt.Errorf("parsing proto file: %w", err)
	}

	// Apply resolver to map proto types to DB types
	// Note: DBType is already set by parser with field name context (for ID fields)
	// Only apply resolver if DBType wasn't set or needs updating
	for _, msg := range model.Messages {
		for _, field := range msg.Fields {
			// Only resolve if DBType is still the default (same as ProtoType)
			// This means the parser didn't set it with field name context
			if field.DBType.Kind == field.ProtoType.Kind && field.DBType.Name == field.ProtoType.Name {
				field.DBType = p.resolver.ResolveWithFieldName(field.ProtoType, field.Name)
			}
		}
	}

	// Extract package name and import path from go_package option
	goPackage := req.FileProto.GetOptions().GetGoPackage()
	packageName := "gen" // default
	importPath := ""     // default
	if goPackage != "" {
		// Handle both "path/to/package" and "path/to/package;package_name" formats
		if semicolonIdx := strings.Index(goPackage, ";"); semicolonIdx != -1 {
			// Format: "path/to/package;package_name"
			importPath = goPackage[:semicolonIdx]
			packageName = goPackage[semicolonIdx+1:]
		} else {
			// Format: "path/to/package"
			importPath = goPackage
			parts := strings.Split(goPackage, "/")
			if len(parts) > 0 {
				packageName = parts[len(parts)-1]
			}
		}
	}

	// Add package declaration once at the top
	var allCode string
	allCode += "// Code generated by protoc-gen-go-mapper. DO NOT EDIT.\n\n"
	allCode += "package " + packageName + "\n\n"

	// Set the generated package name on the generator for type qualification
	p.generator.SetGeneratedPackage(packageName)

	// Add import statements
	allCode += "import (\n"
	// Use the db_package from config if provided, otherwise derive from proto import path
	if p.cfg.DBPackage != "" {
		allCode += "\t\"" + p.cfg.DBPackage + "\"\n"
	} else if importPath != "" {
		dbImportPath := strings.TrimSuffix(importPath, "/gen") + "/db"
		allCode += "\t\"" + dbImportPath + "\"\n"
	} else {
		allCode += "\t\"db\"\n"
	}

	// Add time import only if using old-style helpers (non-generic mode)
	if len(p.cfg.TypeConversions) > 0 {
		allCode += "\t\"time\"\n"
	}

	// Add uuid and pgtype imports (needed for both modes)
	allCode += "\t\"github.com/google/uuid\"\n"
	allCode += "\t\"github.com/jackc/pgx/v5/pgtype\"\n"

	// Alias timestamppb import if it conflicts with the local package name
	if packageName == "timestamppb" {
		allCode += "\ttimestamppb \"google.golang.org/protobuf/types/known/timestamppb\"\n"
	} else {
		allCode += "\t\"google.golang.org/protobuf/types/known/timestamppb\"\n"
	}
	allCode += ")\n\n"

	// Add helper functions for nullable conversions
	// Inline generic converters when using generic mode
	if len(p.cfg.TypeConversions) == 0 {
		// Add inline generic converter functions
		allCode += "// Generic converter functions\n"
		allCode += "func ConvertUUID[T string | *string](v pgtype.UUID) T {\n"
		allCode += "\tif v.Valid {\n"
		allCode += "\t\ts := uuid.UUID(v.Bytes).String()\n"
		allCode += "\t\tvar t T\n"
		allCode += "\t\tswitch any(t).(type) {\n"
		allCode += "\t\tcase string:\n"
		allCode += "\t\t\treturn any(s).(T)\n"
		allCode += "\t\tcase *string:\n"
		allCode += "\t\t\treturn any(&s).(T)\n"
		allCode += "\t\t}\n"
		allCode += "\t}\n"
		allCode += "\tvar zero T\n"
		allCode += "\treturn zero\n"
		allCode += "}\n\n"

		allCode += "func ConvertTimestamp[T *timestamppb.Timestamp](v pgtype.Timestamptz) T {\n"
		allCode += "\tif v.Valid {\n"
		allCode += "\t\treturn timestamppb.New(v.Time)\n"
		allCode += "\t}\n"
		allCode += "\tvar zero T\n"
		allCode += "\treturn zero\n"
		allCode += "}\n\n"

		allCode += "func ConvertText[T string | *string](v pgtype.Text) T {\n"
		allCode += "\tif v.Valid {\n"
		allCode += "\t\tvar t T\n"
		allCode += "\t\tswitch any(t).(type) {\n"
		allCode += "\t\tcase string:\n"
		allCode += "\t\t\treturn any(v.String).(T)\n"
		allCode += "\t\tcase *string:\n"
		allCode += "\t\t\treturn any(&v.String).(T)\n"
		allCode += "\t\t}\n"
		allCode += "\t}\n"
		allCode += "\tvar zero T\n"
		allCode += "\treturn zero\n"
		allCode += "}\n\n"

		// Reverse converters for ToDB functions
		allCode += "func ConvertUUIDToDB(v string) pgtype.UUID {\n"
		allCode += "\tif u, err := uuid.Parse(v); err == nil {\n"
		allCode += "\t\treturn pgtype.UUID{Bytes: u, Valid: true}\n"
		allCode += "\t}\n"
		allCode += "\treturn pgtype.UUID{}\n"
		allCode += "}\n\n"

		allCode += "func ConvertUUIDPtrToDB(v *string) pgtype.UUID {\n"
		allCode += "\tif v != nil {\n"
		allCode += "\t\tif u, err := uuid.Parse(*v); err == nil {\n"
		allCode += "\t\t\treturn pgtype.UUID{Bytes: u, Valid: true}\n"
		allCode += "\t\t}\n"
		allCode += "\t}\n"
		allCode += "\treturn pgtype.UUID{}\n"
		allCode += "}\n\n"

		allCode += "func ConvertTextToDB(v *string) pgtype.Text {\n"
		allCode += "\tif v != nil {\n"
		allCode += "\t\treturn pgtype.Text{String: *v, Valid: true}\n"
		allCode += "\t}\n"
		allCode += "\treturn pgtype.Text{}\n"
		allCode += "}\n\n"

		allCode += "func ConvertTimestampToDB(v *timestamppb.Timestamp) pgtype.Timestamptz {\n"
		allCode += "\tif v != nil {\n"
		allCode += "\t\treturn pgtype.Timestamptz{Time: v.AsTime(), Valid: true}\n"
		allCode += "\t}\n"
		allCode += "\treturn pgtype.Timestamptz{}\n"
		allCode += "}\n\n"
	} else {
		// Add custom helper functions from configuration
		if len(p.cfg.HelperFunctions) > 0 {
			for _, helper := range p.cfg.HelperFunctions {
				if helper.Body != "" {
					allCode += "func " + helper.Name + " " + helper.Body + "\n"
				} else if helper.Signature != "" {
					allCode += "func " + helper.Name + " " + helper.Signature + " { /* TODO: implement */ }\n"
				}
			}
			allCode += "\n"
		}

		// Only add default helpers if type_conversions are configured (backward compatibility)
		if len(p.cfg.TypeConversions) > 0 {
			// Add default helper functions (if not overridden by config)
			defaultHelpers := map[string]string{
				"newInt32":                    "func newInt32(v int32, valid bool) *int32 { if valid { return &v }; return nil }",
				"newInt64":                    "func newInt64(v int64, valid bool) *int64 { if valid { return &v }; return nil }",
				"newBool":                     "func newBool(v bool, valid bool) *bool { if valid { return &v }; return nil }",
				"newString":                   "func newString(v string, valid bool) *string { if valid { return &v }; return nil }",
				"newFloat64":                  "func newFloat64(v float64, valid bool) *float64 { if valid { return &v }; return nil }",
				"newTimeString":               "func newTimeString(v time.Time, valid bool) *string { if valid { s := v.Format(\"2006-01-02\"); return &s }; return nil }",
				"newText":                     "func newText(v *string) pgtype.Text { if v != nil { return pgtype.Text{String: *v, Valid: true} }; return pgtype.Text{} }",
				"newInt8":                     "func newInt8(v *int64) pgtype.Int8 { if v != nil { return pgtype.Int8{Int64: *v, Valid: true} }; return pgtype.Int8{} }",
				"newBoolPg":                   "func newBoolPg(v *bool) pgtype.Bool { if v != nil { return pgtype.Bool{Bool: *v, Valid: true} }; return pgtype.Bool{} }",
				"newUUID":                     "func newUUID(v *string) pgtype.UUID { if v != nil { if u, err := uuid.Parse(*v); err == nil { return pgtype.UUID{Bytes: u, Valid: true} } }; return pgtype.UUID{} }",
				"newStringFromUUID":           "func newStringFromUUID(v pgtype.UUID) *string { if v.Valid { s := uuid.UUID(v.Bytes).String(); return &s }; return nil }",
				"newUUIDFromString":           "func newUUIDFromString(v string) pgtype.UUID { if u, err := uuid.Parse(v); err == nil { return pgtype.UUID{Bytes: u, Valid: true} }; return pgtype.UUID{} }",
				"newStringFromUUIDNonPtr":     "func newStringFromUUIDNonPtr(v pgtype.UUID) string { if v.Valid { return uuid.UUID(v.Bytes).String() }; return \"\" }",
				"newStringFromText":           "func newStringFromText(v pgtype.Text) *string { if v.Valid { return &v.String }; return nil }",
				"newTimestamptz":              "func newTimestamptz(v time.Time) pgtype.Timestamptz { return pgtype.Timestamptz{Time: v, Valid: true} }",
				"newTimestamptzFromTimestamp": "func newTimestamptzFromTimestamp(v *timestamppb.Timestamp) pgtype.Timestamptz { if v != nil { return pgtype.Timestamptz{Time: v.AsTime(), Valid: true} }; return pgtype.Timestamptz{} }",
				"newTimestampFromTimestamptz": "func newTimestampFromTimestamptz(v pgtype.Timestamptz) *timestamppb.Timestamp { if v.Valid { return timestamppb.New(v.Time) }; return nil }",
				"newNullString":               "func newNullString(v *string) pgtype.Text { if v != nil { return pgtype.Text{String: *v, Valid: true} }; return pgtype.Text{} }",
			}

			// Track which helpers were provided by config
			configHelpers := make(map[string]bool)
			for _, helper := range p.cfg.HelperFunctions {
				configHelpers[helper.Name] = true
			}

			// Add default helpers that weren't overridden
			for name, body := range defaultHelpers {
				if !configHelpers[name] {
					allCode += body + "\n"
				}
			}
			allCode += "\n"
		}
	}

	// Generate response type helpers for messages ending with configured suffix
	// These handle array data + metadata conversion
	// Do this before the message loop so it processes all messages regardless of the messages filter
	for _, msg := range model.Messages {
		responseSuffix := p.cfg.ResponsePatterns.ResponseSuffix
		if responseSuffix == "" {
			responseSuffix = "Response"
		}

		if strings.HasSuffix(msg.Name, responseSuffix) {
			// Find the data field using configured pattern
			dataFieldName := p.cfg.ResponsePatterns.DataField
			if dataFieldName == "" {
				dataFieldName = "data"
			}

			var dataField *schema.Field
			var hasTotal, hasPage, hasLimit bool
			for _, field := range msg.Fields {
				if strings.ToLower(field.Name) == dataFieldName {
					dataField = field
				}
				if strings.ToLower(field.Name) == p.cfg.ResponsePatterns.TotalField {
					hasTotal = true
				}
				if strings.ToLower(field.Name) == p.cfg.ResponsePatterns.PageField {
					hasPage = true
				}
				if strings.ToLower(field.Name) == p.cfg.ResponsePatterns.LimitField {
					hasLimit = true
				}
			}

			if dataField != nil {
				elementType := dataField.ProtoType.Name

				// Get the SQLC type name for the element type
				// First check response_type_mappings for response messages
				dbTypeName := ""
				hasMapping := false

				// Check response_type_mappings first (for response messages)
				if p.cfg.ResponseTypeMappings != nil {
					if sqlcType, ok := p.cfg.ResponseTypeMappings[msg.Name]; ok {
						dbTypeName = sqlcType
						hasMapping = true
					}
				}

				// If not found in response_type_mappings, check type_mappings
				if !hasMapping {
					for srcType, dstType := range p.cfg.TypeMappings {
						if srcType == elementType {
							// proto type is the key, SQLC type is the value
							dbTypeName = dstType
							hasMapping = true
							break
						}
						if dstType == elementType {
							// proto type is the value (reverse mapping), SQLC type is the key
							dbTypeName = srcType
							hasMapping = true
							break
						}
					}
				}

				// Skip if no mapping found
				if !hasMapping {
					continue
				}

				// Find the target message for field mapping
				var targetMsg *schema.Message
				for _, m := range model.Messages {
					if m.Name == elementType {
						targetMsg = m
						break
					}
				}

				// Case 1: List response with pagination (repeated data + Total/Page/Limit)
				if dataField.ProtoType.IsSlice && hasTotal && hasPage && hasLimit {
					// Generate response helper function with inline array conversion
					allCode += fmt.Sprintf("// ToProto%sFromRows converts SQLC rows to %s response\n", msg.Name, msg.Name)
					allCode += fmt.Sprintf("func ToProto%sFromRows(rows []sqlc.%s, total int64, page, limit int32) *%s {\n",
						msg.Name, dbTypeName, msg.Name)
					allCode += "\tif rows == nil {\n"
					allCode += "\t\treturn nil\n"
					allCode += "\t}\n"
					allCode += "\titems := make([]*" + elementType + ", len(rows))\n"
					allCode += "\tfor i, item := range rows {\n"
					allCode += "\t\titems[i] = &" + elementType + "{\n"

					// Map fields from source row to target message using handler system
					if targetMsg != nil {
						for _, field := range targetMsg.Fields {
							dbFieldName := toPascalCase(field.Name)
							protoFieldName := toProtoPascalCase(field.Name)

							// Skip fields configured in response_patterns.skip_fields
							shouldSkip := false
							if len(p.cfg.ResponsePatterns.SkipFields) > 0 {
								for _, skipField := range p.cfg.ResponsePatterns.SkipFields {
									if dbFieldName == skipField {
										shouldSkip = true
										break
									}
								}
							}
							if shouldSkip {
								continue
							}

							// Use generic converters if no type_conversions configured
							if len(p.cfg.TypeConversions) == 0 {
								// Auto-detect and use generic converters for common types
								protoFieldType := field.ProtoType.Name
								dbFieldType := field.DBType.Name

								// UUID fields (string <-> pgtype.UUID)
								if protoFieldType == "string" && dbFieldType == "pgtype.UUID" {
									if field.Optional {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertUUID[*string](item.%s),\n", protoFieldName, dbFieldName)
									} else {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertUUID[string](item.%s),\n", protoFieldName, dbFieldName)
									}
									continue
								}

								// Timestamp fields (google.protobuf.Timestamp <-> pgtype.Timestamptz)
								if protoFieldType == "Timestamp" || protoFieldType == "google.protobuf.Timestamp" {
									if dbFieldType == "pgtype.Timestamptz" {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertTimestamp[*timestamppb.Timestamp](item.%s),\n", protoFieldName, dbFieldName)
										continue
									}
								}

								// Text fields (string <-> pgtype.Text)
								if protoFieldType == "string" && dbFieldType == "pgtype.Text" {
									if field.Optional {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertText[*string](item.%s),\n", protoFieldName, dbFieldName)
									} else {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertText[string](item.%s),\n", protoFieldName, dbFieldName)
									}
									continue
								}

								// Numeric fields (int32, int64, float64, bool)
								if protoFieldType == "int32" && dbFieldType == "int32" {
									if field.Optional {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertInt32[*int32](item.%s, true),\n", protoFieldName, dbFieldName)
									} else {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertInt32[int32](item.%s, true),\n", protoFieldName, dbFieldName)
									}
									continue
								}

								if protoFieldType == "int64" && dbFieldType == "int64" {
									if field.Optional {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertInt64[*int64](item.%s, true),\n", protoFieldName, dbFieldName)
									} else {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertInt64[int64](item.%s, true),\n", protoFieldName, dbFieldName)
									}
									continue
								}

								if protoFieldType == "float64" && dbFieldType == "float64" {
									if field.Optional {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertFloat64[*float64](item.%s, true),\n", protoFieldName, dbFieldName)
									} else {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertFloat64[float64](item.%s, true),\n", protoFieldName, dbFieldName)
									}
									continue
								}

								if protoFieldType == "bool" && dbFieldType == "bool" {
									if field.Optional {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertBool[*bool](item.%s, true),\n", protoFieldName, dbFieldName)
									} else {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertBool[bool](item.%s, true),\n", protoFieldName, dbFieldName)
									}
									continue
								}
							}

							// Check type-based handlers first
							if p.typeHandlerReg != nil {
								if h := p.typeHandlerReg.Find(field, dbTypeName); h != nil {
									expr, err := h.GenerateToProto(field, dbFieldName, protoFieldName, dbTypeName)
									if err != nil {
										fmt.Printf("Warning: type handler error for field %s: %v\n", field.Name, err)
									} else if expr != "" {
										// Replace {variable} placeholder with item
										expr = strings.Replace(expr, "{variable}", "item", -1)

										// Apply pointer strategy if configured
										if typeConvHandler, ok := h.(*handler.TypeConversionHandler); ok {
											strategy := typeConvHandler.PointerStrategy()
											if strategy == "" && p.cfg.PointerSettings.DefaultStrategy != "" {
												strategy = p.cfg.PointerSettings.DefaultStrategy
											}
											if fieldStrategy, ok := p.cfg.PointerSettings.FieldStrategies[protoFieldName]; ok {
												strategy = fieldStrategy
											}

											// Apply pointer strategy
											if strategy == "omit" && field.Optional {
												// Skip field if strategy is omit and field is optional
												continue
											}
										}

										allCode += "\t\t\t" + expr + ",\n"
										continue
									}
								}
							}

							// Check field name handlers
							if p.handlerReg != nil {
								if h := p.handlerReg.Find(field, dbTypeName); h != nil {
									// Use handler for conversion
									expr, err := h.GenerateToProto(field, dbFieldName, protoFieldName, dbTypeName)
									if err != nil {
										// Log error but continue with default
										fmt.Printf("Warning: handler error for field %s: %v\n", field.Name, err)
									} else if expr != "" {
										// Prepend item. prefix for response helpers
										allCode += "\t\t\t" + strings.Replace(expr, ".", "item.", 1) + ",\n"
										continue
									}
								}
							}

							// Direct assignment for other fields (fallback)
							allCode += fmt.Sprintf("\t\t\t%s: item.%s,\n", protoFieldName, dbFieldName)
						}
					}

					allCode += "\t\t}\n"
					allCode += "\t}\n"
					allCode += "\treturn &" + msg.Name + "{\n"
					allCode += "\t\tData: items,\n"
					allCode += "\t\tTotal: total,\n"
					allCode += "\t\tPage: page,\n"
					allCode += "\t\tLimit: limit,\n"
					allCode += "\t}\n"
					allCode += "}\n\n"
				}

				// Case 2: List response without pagination (repeated data only)
				if dataField.ProtoType.IsSlice && !hasTotal && !hasPage && !hasLimit {
					// Generate response helper function with inline array conversion
					// Use the SQLC type directly for the conversion
					allCode += fmt.Sprintf("// ToProto%sFromRows converts SQLC rows to %s response\n", msg.Name, msg.Name)
					allCode += fmt.Sprintf("func ToProto%sFromRows(rows []sqlc.%s) *%s {\n",
						msg.Name, dbTypeName, msg.Name)
					allCode += "\tif rows == nil {\n"
					allCode += "\t\treturn nil\n"
					allCode += "\t}\n"
					allCode += "\titems := make([]*" + elementType + ", len(rows))\n"
					allCode += "\tfor i, item := range rows {\n"
					allCode += "\t\titems[i] = &" + elementType + "{\n"

					// Map fields from source row to target message using handler system
					if targetMsg != nil {
						for _, field := range targetMsg.Fields {
							dbFieldName := toPascalCase(field.Name)
							protoFieldName := toProtoPascalCase(field.Name)

							// Skip fields configured in response_patterns.skip_fields
							shouldSkip := false
							if len(p.cfg.ResponsePatterns.SkipFields) > 0 {
								for _, skipField := range p.cfg.ResponsePatterns.SkipFields {
									if dbFieldName == skipField {
										shouldSkip = true
										break
									}
								}
							}
							if shouldSkip {
								continue
							}

							// Use generic converters if no type_conversions configured
							if len(p.cfg.TypeConversions) == 0 {
								// Auto-detect and use generic converters for common types
								protoFieldType := field.ProtoType.Name
								dbFieldType := field.DBType.Name

								// UUID fields (string <-> pgtype.UUID)
								if protoFieldType == "string" && dbFieldType == "pgtype.UUID" {
									if field.Optional {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertUUID[*string](item.%s),\n", protoFieldName, dbFieldName)
									} else {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertUUID[string](item.%s),\n", protoFieldName, dbFieldName)
									}
									continue
								}

								// Timestamp fields (google.protobuf.Timestamp <-> pgtype.Timestamptz)
								if protoFieldType == "Timestamp" || protoFieldType == "google.protobuf.Timestamp" {
									if dbFieldType == "pgtype.Timestamptz" {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertTimestamp[*timestamppb.Timestamp](item.%s),\n", protoFieldName, dbFieldName)
										continue
									}
								}

								// Text fields (string <-> pgtype.Text)
								if protoFieldType == "string" && dbFieldType == "pgtype.Text" {
									if field.Optional {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertText[*string](item.%s),\n", protoFieldName, dbFieldName)
									} else {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertText[string](item.%s),\n", protoFieldName, dbFieldName)
									}
									continue
								}

								// Numeric fields (int32, int64, float64, bool)
								if protoFieldType == "int32" && dbFieldType == "int32" {
									if field.Optional {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertInt32[*int32](item.%s, true),\n", protoFieldName, dbFieldName)
									} else {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertInt32[int32](item.%s, true),\n", protoFieldName, dbFieldName)
									}
									continue
								}

								if protoFieldType == "int64" && dbFieldType == "int64" {
									if field.Optional {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertInt64[*int64](item.%s, true),\n", protoFieldName, dbFieldName)
									} else {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertInt64[int64](item.%s, true),\n", protoFieldName, dbFieldName)
									}
									continue
								}

								if protoFieldType == "float64" && dbFieldType == "float64" {
									if field.Optional {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertFloat64[*float64](item.%s, true),\n", protoFieldName, dbFieldName)
									} else {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertFloat64[float64](item.%s, true),\n", protoFieldName, dbFieldName)
									}
									continue
								}

								if protoFieldType == "bool" && dbFieldType == "bool" {
									if field.Optional {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertBool[*bool](item.%s, true),\n", protoFieldName, dbFieldName)
									} else {
										allCode += fmt.Sprintf("\t\t\t%s: ConvertBool[bool](item.%s, true),\n", protoFieldName, dbFieldName)
									}
									continue
								}
							}

							// Check type-based handlers first
							if p.typeHandlerReg != nil {
								if h := p.typeHandlerReg.Find(field, dbTypeName); h != nil {
									expr, err := h.GenerateToProto(field, dbFieldName, protoFieldName, dbTypeName)
									if err != nil {
										fmt.Printf("Warning: type handler error for field %s: %v\n", field.Name, err)
									} else if expr != "" {
										// Replace {variable} placeholder with item
										expr = strings.Replace(expr, "{variable}", "item", -1)

										// Apply pointer strategy if configured
										if typeConvHandler, ok := h.(*handler.TypeConversionHandler); ok {
											strategy := typeConvHandler.PointerStrategy()
											if strategy == "" && p.cfg.PointerSettings.DefaultStrategy != "" {
												strategy = p.cfg.PointerSettings.DefaultStrategy
											}
											if fieldStrategy, ok := p.cfg.PointerSettings.FieldStrategies[protoFieldName]; ok {
												strategy = fieldStrategy
											}

											// Apply pointer strategy
											if strategy == "omit" && field.Optional {
												// Skip field if strategy is omit and field is optional
												continue
											}
										}

										allCode += "\t\t\t" + expr + ",\n"
										continue
									}
								}
							}

							// Check field name handlers
							if p.handlerReg != nil {
								if h := p.handlerReg.Find(field, dbTypeName); h != nil {
									// Use handler for conversion
									expr, err := h.GenerateToProto(field, dbFieldName, protoFieldName, dbTypeName)
									if err != nil {
										// Log error but continue with default
										fmt.Printf("Warning: handler error for field %s: %v\n", field.Name, err)
									} else if expr != "" {
										// Prepend item. prefix for response helpers
										allCode += "\t\t\t" + strings.Replace(expr, ".", "item.", 1) + ",\n"
										continue
									}
								}
							}

							// Direct assignment for other fields (fallback)
							allCode += fmt.Sprintf("\t\t\t%s: item.%s,\n", protoFieldName, dbFieldName)
						}
					}

					allCode += "\t\t}\n"
					allCode += "\t}\n"
					allCode += "\treturn &" + msg.Name + "{\n"
					allCode += "\t\tData: items,\n"
					allCode += "\t}\n"
					allCode += "}\n\n"
				}

				// Case 3: Single item response (non-repeated data)
				if !dataField.ProtoType.IsSlice {
					// Generate response helper function for single item
					// Use the DB type name directly (not the Row type from reverse mapping)
					allCode += fmt.Sprintf("// ToProto%sFromRow converts SQLC row to %s response\n", msg.Name, msg.Name)
					allCode += fmt.Sprintf("func ToProto%sFromRow(row sqlc.%s) *%s {\n",
						msg.Name, dbTypeName, msg.Name)
					allCode += "\treturn &" + msg.Name + "{\n"
					allCode += "\t\tData: ToProto" + elementType + "(row),\n"
					allCode += "\t}\n"
					allCode += "}\n\n"
				}
			}
		}
	}

	// Build mapper graphs for each message
	for _, msg := range model.Messages {
		// Skip messages not in the configured list (if list is non-empty)
		if len(p.cfg.Messages) > 0 {
			found := false
			for _, cfgMsg := range p.cfg.Messages {
				if cfgMsg == msg.Name {
					found = true
					break
				}
			}
			if !found {
				continue
			}
		}

		protoToDB := graph.NewMapper(msg.Name, msg.Name)
		dbToProto := graph.NewMapper(msg.Name, msg.Name)

		// Add field mappings
		for _, field := range msg.Fields {
			err := protoToDB.AddField(field.Name, field.Name, field.ProtoType, field.DBType, p.registry)
			if err != nil {
				return fmt.Errorf("adding field mapping for %s.%s: %w", msg.Name, field.Name, err)
			}

			err = dbToProto.AddField(field.Name, field.Name, field.DBType, field.ProtoType, p.registry)
			if err != nil {
				return fmt.Errorf("adding field mapping for %s.%s: %w", msg.Name, field.Name, err)
			}
		}

		// Generate code
		useGenericConverters := len(p.cfg.TypeConversions) == 0
		code, err := p.generator.Generate(msg, protoToDB, dbToProto, p.cfg.TypeMappings, useGenericConverters)
		if err != nil {
			return fmt.Errorf("generating code for %s: %w", msg.Name, err)
		}

		allCode += code
	}

	// Write output
	_, err = w.Write([]byte(allCode))
	if err != nil {
		return fmt.Errorf("writing output: %w", err)
	}

	return nil
}

// GenerateRequest represents a generation request.
type GenerateRequest struct {
	FileProto *descriptorpb.FileDescriptorProto
}

// toPascalCase converts snake_case to PascalCase
func toPascalCase(s string) string {
	// Special case for "id" -> "ID"
	if s == "id" {
		return "ID"
	}
	parts := strings.Split(s, "_")
	for i, part := range parts {
		if len(part) > 0 {
			// Handle "id" suffix specially - keep it uppercase
			if part == "id" {
				parts[i] = "ID"
			} else {
				parts[i] = strings.ToUpper(string(part[0])) + strings.ToLower(part[1:])
			}
		}
	}
	return strings.Join(parts, "")
}

// toProtoPascalCase converts snake_case to proto PascalCase (Id not ID)
func toProtoPascalCase(s string) string {
	// Special case for "id" -> "Id"
	if s == "id" {
		return "Id"
	}
	parts := strings.Split(s, "_")
	for i, part := range parts {
		if len(part) > 0 {
			// Handle "id" suffix specially - use "Id" not "ID"
			if part == "id" {
				parts[i] = "Id"
			} else {
				parts[i] = strings.ToUpper(string(part[0])) + strings.ToLower(part[1:])
			}
		}
	}
	return strings.Join(parts, "")
}

// toCamelCase converts snake_case to camelCase
func toCamelCase(s string) string {
	// Special case for "id" -> "id"
	if s == "id" {
		return "id"
	}
	parts := strings.Split(s, "_")
	for i, part := range parts {
		if len(part) > 0 {
			if i == 0 {
				// First word is lowercase
				parts[i] = strings.ToLower(part)
			} else {
				// Subsequent words are capitalized
				if part == "id" {
					parts[i] = "Id"
				} else {
					parts[i] = strings.ToUpper(string(part[0])) + strings.ToLower(part[1:])
				}
			}
		}
	}
	return strings.Join(parts, "")
}
