// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type User struct {
	ID     int32
	Name   string
	Email  string
	Age    sql.NullInt32
	Active sql.NullBool
}
