// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
)

type OrderStatus string

const (
	OrderStatusPending    OrderStatus = "pending"
	OrderStatusProcessing OrderStatus = "processing"
	OrderStatusShipped    OrderStatus = "shipped"
	OrderStatusDelivered  OrderStatus = "delivered"
	OrderStatusCancelled  OrderStatus = "cancelled"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus
	Valid       bool // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type Customer struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Phone     sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Order struct {
	ID          uuid.UUID
	CustomerID  uuid.NullUUID
	Status      OrderStatus
	TotalAmount string
	Notes       sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type OrderItem struct {
	ID        uuid.UUID
	OrderID   uuid.NullUUID
	ProductID uuid.NullUUID
	Quantity  int32
	UnitPrice string
	Subtotal  string
}

type Product struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Price       string
	Stock       sql.NullInt32
	CreatedAt   sql.NullTime
}
