// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type SchmPosInventoryTransactionType string

const (
	SchmPosInventoryTransactionTypePURCHASE         SchmPosInventoryTransactionType = "PURCHASE"
	SchmPosInventoryTransactionTypeSALE             SchmPosInventoryTransactionType = "SALE"
	SchmPosInventoryTransactionTypePRODUCTIONUSAGE  SchmPosInventoryTransactionType = "PRODUCTION_USAGE"
	SchmPosInventoryTransactionTypePRODUCTIONRESULT SchmPosInventoryTransactionType = "PRODUCTION_RESULT"
	SchmPosInventoryTransactionTypeRETURN           SchmPosInventoryTransactionType = "RETURN"
	SchmPosInventoryTransactionTypeADJUSTMENT       SchmPosInventoryTransactionType = "ADJUSTMENT"
	SchmPosInventoryTransactionTypeWASTE            SchmPosInventoryTransactionType = "WASTE"
	SchmPosInventoryTransactionTypeTRANSFER         SchmPosInventoryTransactionType = "TRANSFER"
)

func (e *SchmPosInventoryTransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SchmPosInventoryTransactionType(s)
	case string:
		*e = SchmPosInventoryTransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for SchmPosInventoryTransactionType: %T", src)
	}
	return nil
}

type NullSchmPosInventoryTransactionType struct {
	SchmPosInventoryTransactionType SchmPosInventoryTransactionType
	Valid                           bool // Valid is true if SchmPosInventoryTransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSchmPosInventoryTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.SchmPosInventoryTransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SchmPosInventoryTransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSchmPosInventoryTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SchmPosInventoryTransactionType), nil
}

type SchmPosItemType string

const (
	SchmPosItemTypeRAWMATERIAL  SchmPosItemType = "RAW_MATERIAL"
	SchmPosItemTypeSEMIFINISHED SchmPosItemType = "SEMI_FINISHED"
	SchmPosItemTypeFINISHEDGOOD SchmPosItemType = "FINISHED_GOOD"
	SchmPosItemTypePACKAGING    SchmPosItemType = "PACKAGING"
	SchmPosItemTypeSERVICE      SchmPosItemType = "SERVICE"
	SchmPosItemTypeCONSUMABLE   SchmPosItemType = "CONSUMABLE"
)

func (e *SchmPosItemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SchmPosItemType(s)
	case string:
		*e = SchmPosItemType(s)
	default:
		return fmt.Errorf("unsupported scan type for SchmPosItemType: %T", src)
	}
	return nil
}

type NullSchmPosItemType struct {
	SchmPosItemType SchmPosItemType
	Valid           bool // Valid is true if SchmPosItemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSchmPosItemType) Scan(value interface{}) error {
	if value == nil {
		ns.SchmPosItemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SchmPosItemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSchmPosItemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SchmPosItemType), nil
}

type SchmPosProductionOrderStatus string

const (
	SchmPosProductionOrderStatusDRAFT      SchmPosProductionOrderStatus = "DRAFT"
	SchmPosProductionOrderStatusRELEASED   SchmPosProductionOrderStatus = "RELEASED"
	SchmPosProductionOrderStatusINPROGRESS SchmPosProductionOrderStatus = "IN_PROGRESS"
	SchmPosProductionOrderStatusCOMPLETED  SchmPosProductionOrderStatus = "COMPLETED"
	SchmPosProductionOrderStatusCANCELLED  SchmPosProductionOrderStatus = "CANCELLED"
)

func (e *SchmPosProductionOrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SchmPosProductionOrderStatus(s)
	case string:
		*e = SchmPosProductionOrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SchmPosProductionOrderStatus: %T", src)
	}
	return nil
}

type NullSchmPosProductionOrderStatus struct {
	SchmPosProductionOrderStatus SchmPosProductionOrderStatus
	Valid                        bool // Valid is true if SchmPosProductionOrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSchmPosProductionOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SchmPosProductionOrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SchmPosProductionOrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSchmPosProductionOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SchmPosProductionOrderStatus), nil
}

type SchmPosPurchaseStatus string

const (
	SchmPosPurchaseStatusDRAFT     SchmPosPurchaseStatus = "DRAFT"
	SchmPosPurchaseStatusCONFIRMED SchmPosPurchaseStatus = "CONFIRMED"
	SchmPosPurchaseStatusRECEIVED  SchmPosPurchaseStatus = "RECEIVED"
	SchmPosPurchaseStatusCANCELLED SchmPosPurchaseStatus = "CANCELLED"
	SchmPosPurchaseStatusRETURE    SchmPosPurchaseStatus = "RETURE"
)

func (e *SchmPosPurchaseStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SchmPosPurchaseStatus(s)
	case string:
		*e = SchmPosPurchaseStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SchmPosPurchaseStatus: %T", src)
	}
	return nil
}

type NullSchmPosPurchaseStatus struct {
	SchmPosPurchaseStatus SchmPosPurchaseStatus
	Valid                 bool // Valid is true if SchmPosPurchaseStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSchmPosPurchaseStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SchmPosPurchaseStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SchmPosPurchaseStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSchmPosPurchaseStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SchmPosPurchaseStatus), nil
}

type SchmPosSalesStatus string

const (
	SchmPosSalesStatusDRAFT   SchmPosSalesStatus = "DRAFT"
	SchmPosSalesStatusPAID    SchmPosSalesStatus = "PAID"
	SchmPosSalesStatusPARTIAL SchmPosSalesStatus = "PARTIAL"
	SchmPosSalesStatusVOID    SchmPosSalesStatus = "VOID"
)

func (e *SchmPosSalesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SchmPosSalesStatus(s)
	case string:
		*e = SchmPosSalesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SchmPosSalesStatus: %T", src)
	}
	return nil
}

type NullSchmPosSalesStatus struct {
	SchmPosSalesStatus SchmPosSalesStatus
	Valid              bool // Valid is true if SchmPosSalesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSchmPosSalesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SchmPosSalesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SchmPosSalesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSchmPosSalesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SchmPosSalesStatus), nil
}

type SchmPosWarehouseType string

const (
	SchmPosWarehouseTypeMAIN       SchmPosWarehouseType = "MAIN"
	SchmPosWarehouseTypeKITCHEN    SchmPosWarehouseType = "KITCHEN"
	SchmPosWarehouseTypeOUTLET     SchmPosWarehouseType = "OUTLET"
	SchmPosWarehouseTypeBAR        SchmPosWarehouseType = "BAR"
	SchmPosWarehouseTypePRODUCTION SchmPosWarehouseType = "PRODUCTION"
	SchmPosWarehouseTypeTRANSIT    SchmPosWarehouseType = "TRANSIT"
)

func (e *SchmPosWarehouseType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SchmPosWarehouseType(s)
	case string:
		*e = SchmPosWarehouseType(s)
	default:
		return fmt.Errorf("unsupported scan type for SchmPosWarehouseType: %T", src)
	}
	return nil
}

type NullSchmPosWarehouseType struct {
	SchmPosWarehouseType SchmPosWarehouseType
	Valid                bool // Valid is true if SchmPosWarehouseType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSchmPosWarehouseType) Scan(value interface{}) error {
	if value == nil {
		ns.SchmPosWarehouseType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SchmPosWarehouseType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSchmPosWarehouseType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SchmPosWarehouseType), nil
}

type SchmPosBom struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	ProductID      pgtype.UUID
	Version        pgtype.Text
	Active         pgtype.Bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	EffectiveFrom  pgtype.Date
	EffectiveUntil pgtype.Date
}

type SchmPosBranch struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	Code      string
	Name      string
	Phone     pgtype.Text
	Email     pgtype.Text
	Address   pgtype.Text
	Active    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	DeletedBy pgtype.UUID
}

type SchmPosCashMovement struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	CashShiftID  pgtype.UUID
	MovementType pgtype.Text
	Amount       pgtype.Numeric
	Reason       pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type SchmPosCashShift struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	BranchID        pgtype.UUID
	ShiftNo         string
	CashierID       pgtype.UUID
	OpenedAt        pgtype.Timestamptz
	ClosedAt        pgtype.Timestamptz
	OpeningBalance  pgtype.Numeric
	ClosingBalance  pgtype.Numeric
	ExpectedBalance pgtype.Numeric
	Variance        pgtype.Numeric
	Status          pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

type SchmPosCustomer struct {
	ID            pgtype.UUID
	TenantID      pgtype.UUID
	Code          pgtype.Text
	Name          string
	Phone         pgtype.Text
	Email         pgtype.Text
	BirthDate     pgtype.Date
	LoyaltyPoints pgtype.Int8
	MemberSince   pgtype.Date
	Active        pgtype.Bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type SchmPosInventory struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	ItemID       pgtype.UUID
	WarehouseID  pgtype.UUID
	QtyOnHand    pgtype.Numeric
	QtyReserved  pgtype.Numeric
	QtyAvailable pgtype.Numeric
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	BranchID     pgtype.UUID
}

type SchmPosInventoryBatch struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	WarehouseID     pgtype.UUID
	ItemID          pgtype.UUID
	BatchNo         string
	ManufactureDate pgtype.Date
	ExpiredDate     pgtype.Date
	Qty             pgtype.Numeric
	CostPerUnit     pgtype.Numeric
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type SchmPosInventoryTransaction struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	ItemID          pgtype.UUID
	WarehouseID     pgtype.UUID
	TransactionType SchmPosInventoryTransactionType
	ReferenceType   pgtype.Text
	ReferenceID     pgtype.UUID
	QtyIn           pgtype.Numeric
	QtyOut          pgtype.Numeric
	BalanceAfter    pgtype.Numeric
	CreatedAt       pgtype.Timestamptz
	BranchID        pgtype.UUID
	BatchID         pgtype.UUID
}

type SchmPosInventoryWaste struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	WarehouseID pgtype.UUID
	WasteNo     string
	WasteDate   pgtype.Timestamptz
	Reason      pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type SchmPosInventoryWasteItem struct {
	ID      pgtype.UUID
	WasteID pgtype.UUID
	ItemID  pgtype.UUID
	Qty     pgtype.Numeric
	Cost    pgtype.Numeric
	Notes   pgtype.Text
}

type SchmPosItem struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	CategoryID     pgtype.UUID
	BaseUomID      pgtype.UUID
	Code           string
	Sku            pgtype.Text
	Barcode        pgtype.Text
	Name           string
	ItemType       SchmPosItemType
	CostPrice      pgtype.Numeric
	SellingPrice   pgtype.Numeric
	MinimumStock   pgtype.Numeric
	TrackInventory bool
	Active         bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	DeletedBy      pgtype.UUID
}

type SchmPosItemCategory struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	ParentID    pgtype.UUID
	Code        string
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	DeletedBy   pgtype.UUID
}

type SchmPosItemUom struct {
	ID               pgtype.UUID
	TenantID         pgtype.UUID
	ItemID           pgtype.UUID
	UomID            pgtype.UUID
	ConversionFactor pgtype.Numeric
	IsBase           bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type SchmPosKitchenOrder struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	SaleID    pgtype.UUID
	KitchenNo pgtype.Text
	Status    pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type SchmPosKitchenOrderItem struct {
	ID             pgtype.UUID
	KitchenOrderID pgtype.UUID
	SaleItemID     pgtype.UUID
	Status         pgtype.Text
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
}

type SchmPosMenu struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	CategoryID pgtype.UUID
	ItemID     pgtype.UUID
	Code       pgtype.Text
	Name       pgtype.Text
	Active     pgtype.Bool
	CreatedAt  pgtype.Timestamptz
}

type SchmPosMenuCategory struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	Code      pgtype.Text
	Name      pgtype.Text
	Active    pgtype.Bool
	CreatedAt pgtype.Timestamptz
}

type SchmPosMenuPrice struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	MenuID         pgtype.UUID
	BranchID       pgtype.UUID
	Price          pgtype.Numeric
	EffectiveFrom  pgtype.Timestamptz
	EffectiveUntil pgtype.Timestamptz
}

type SchmPosOutbox struct {
	ID            pgtype.UUID
	TenantID      pgtype.UUID
	AggregateID   pgtype.UUID
	Topic         string
	Key           []byte
	Payload       []byte
	Headers       []byte
	Attempts      pgtype.Int4
	Status        interface{}
	ErrorMsg      pgtype.Text
	RetryCount    pgtype.Int8
	RetryAt       pgtype.Timestamp
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	NextAttemptAt pgtype.Timestamptz
}

type SchmPosProductionOrder struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	BranchID       pgtype.UUID
	WarehouseID    pgtype.UUID
	BomID          pgtype.UUID
	ProductionNo   string
	ProductionDate pgtype.Date
	Status         SchmPosProductionOrderStatus
	QtyTarget      pgtype.Numeric
	QtyActual      pgtype.Numeric
	ExpectedYield  pgtype.Numeric
	ActualYield    pgtype.Numeric
	WasteQty       pgtype.Numeric
	Notes          pgtype.Text
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	LossQty        pgtype.Numeric
}

type SchmPosProductionOrderMaterial struct {
	ID                pgtype.UUID
	TenantID          pgtype.UUID
	ProductionOrderID pgtype.UUID
	ItemID            pgtype.UUID
	UomID             pgtype.UUID
	BatchID           pgtype.UUID
	QtyPlanned        pgtype.Numeric
	QtyActual         pgtype.Numeric
	UnitCost          pgtype.Numeric
	TotalCost         pgtype.Numeric
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type SchmPosProductionOrderResult struct {
	ID                pgtype.UUID
	TenantID          pgtype.UUID
	ProductionOrderID pgtype.UUID
	ItemID            pgtype.UUID
	UomID             pgtype.UUID
	BatchID           pgtype.UUID
	Qty               pgtype.Numeric
	UnitCost          pgtype.Numeric
	TotalCost         pgtype.Numeric
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type SchmPosPurchase struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	SupplierID   pgtype.UUID
	PurchaseNo   string
	PurchaseDate pgtype.Date
	TotalAmount  pgtype.Numeric
	Status       SchmPosPurchaseStatus
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	BranchID     pgtype.UUID
	WarehouseID  pgtype.UUID
}

type SchmPosSale struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	CustomerID     pgtype.UUID
	InvoiceNo      string
	Subtotal       pgtype.Numeric
	Discount       pgtype.Numeric
	Tax            pgtype.Numeric
	Total          pgtype.Numeric
	Status         SchmPosSalesStatus
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	BranchID       pgtype.UUID
	CashShiftID    pgtype.UUID
	KitchenOrderID pgtype.UUID
}

type SchmPosStockOpname struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	WarehouseID pgtype.UUID
	OpnameNo    string
	OpnameDate  pgtype.Timestamptz
	Status      string
	Notes       pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type SchmPosStockOpnameItem struct {
	ID          pgtype.UUID
	OpnameID    pgtype.UUID
	ItemID      pgtype.UUID
	SystemQty   pgtype.Numeric
	ActualQty   pgtype.Numeric
	VarianceQty pgtype.Numeric
	CreatedAt   pgtype.Timestamptz
}

type SchmPosStockTransfer struct {
	ID                     pgtype.UUID
	TenantID               pgtype.UUID
	TransferNo             string
	SourceWarehouseID      pgtype.UUID
	DestinationWarehouseID pgtype.UUID
	TransferDate           pgtype.Timestamptz
	Status                 string
	Notes                  pgtype.Text
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	DeletedAt              pgtype.Timestamptz
}

type SchmPosStockTransferItem struct {
	ID         pgtype.UUID
	TransferID pgtype.UUID
	ItemID     pgtype.UUID
	UomID      pgtype.UUID
	Qty        pgtype.Numeric
	CreatedAt  pgtype.Timestamptz
}

type SchmPosSupplier struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	Code      string
	Name      string
	Phone     pgtype.Text
	Email     pgtype.Text
	Address   pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type SchmPosUom struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	Code        string
	Name        string
	Symbol      string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	DeletedBy   pgtype.UUID
}

type SchmPosWarehouse struct {
	ID            pgtype.UUID
	TenantID      pgtype.UUID
	BranchID      pgtype.UUID
	Code          string
	Name          string
	WarehouseType SchmPosWarehouseType
	Active        pgtype.Bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}
