// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchDeleteUOM = `-- name: BatchDeleteUOM :many
UPDATE schm_pos.uoms
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE
    id = ANY($1::uuid[])
RETURNING id, tenant_id, code, name, symbol, description, created_at, updated_at, deleted_at, deleted_by
`

func (q *Queries) BatchDeleteUOM(ctx context.Context, ids []pgtype.UUID) ([]SchmPosUom, error) {
	rows, err := q.db.Query(ctx, batchDeleteUOM, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SchmPosUom
	for rows.Next() {
		var i SchmPosUom
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.Symbol,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const batchRestoreUOM = `-- name: BatchRestoreUOM :many
UPDATE schm_pos.uoms
SET
    deleted_at = NULL,
    updated_at = NOW()
WHERE
    id = ANY($1::uuid[])
RETURNING id, tenant_id, code, name, symbol, description, created_at, updated_at, deleted_at, deleted_by
`

func (q *Queries) BatchRestoreUOM(ctx context.Context, ids []pgtype.UUID) ([]SchmPosUom, error) {
	rows, err := q.db.Query(ctx, batchRestoreUOM, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SchmPosUom
	for rows.Next() {
		var i SchmPosUom
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.Symbol,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const changeAttemptCount = `-- name: ChangeAttemptCount :one
UPDATE schm_pos.outbox SET attempts=$1 WHERE id=$2 RETURNING id, tenant_id, aggregate_id, topic, key, payload, headers, attempts, status, error_msg, retry_count, retry_at, created_at, updated_at, next_attempt_at
`

type ChangeAttemptCountParams struct {
	Attempts pgtype.Int4
	ID       pgtype.UUID
}

func (q *Queries) ChangeAttemptCount(ctx context.Context, arg ChangeAttemptCountParams) (SchmPosOutbox, error) {
	row := q.db.QueryRow(ctx, changeAttemptCount, arg.Attempts, arg.ID)
	var i SchmPosOutbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AggregateID,
		&i.Topic,
		&i.Key,
		&i.Payload,
		&i.Headers,
		&i.Attempts,
		&i.Status,
		&i.ErrorMsg,
		&i.RetryCount,
		&i.RetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextAttemptAt,
	)
	return i, err
}

const changeRetryCount = `-- name: ChangeRetryCount :one
UPDATE schm_pos.outbox SET retry_count=$1 WHERE id=$2 RETURNING id, tenant_id, aggregate_id, topic, key, payload, headers, attempts, status, error_msg, retry_count, retry_at, created_at, updated_at, next_attempt_at
`

type ChangeRetryCountParams struct {
	RetryCount pgtype.Int8
	ID         pgtype.UUID
}

func (q *Queries) ChangeRetryCount(ctx context.Context, arg ChangeRetryCountParams) (SchmPosOutbox, error) {
	row := q.db.QueryRow(ctx, changeRetryCount, arg.RetryCount, arg.ID)
	var i SchmPosOutbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AggregateID,
		&i.Topic,
		&i.Key,
		&i.Payload,
		&i.Headers,
		&i.Attempts,
		&i.Status,
		&i.ErrorMsg,
		&i.RetryCount,
		&i.RetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextAttemptAt,
	)
	return i, err
}

const changeStatusEvent = `-- name: ChangeStatusEvent :one
UPDATE schm_pos.outbox SET status=$1 WHERE id = $2 RETURNING id, tenant_id, aggregate_id, topic, key, payload, headers, attempts, status, error_msg, retry_count, retry_at, created_at, updated_at, next_attempt_at
`

type ChangeStatusEventParams struct {
	Status interface{}
	ID     pgtype.UUID
}

func (q *Queries) ChangeStatusEvent(ctx context.Context, arg ChangeStatusEventParams) (SchmPosOutbox, error) {
	row := q.db.QueryRow(ctx, changeStatusEvent, arg.Status, arg.ID)
	var i SchmPosOutbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AggregateID,
		&i.Topic,
		&i.Key,
		&i.Payload,
		&i.Headers,
		&i.Attempts,
		&i.Status,
		&i.ErrorMsg,
		&i.RetryCount,
		&i.RetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextAttemptAt,
	)
	return i, err
}

const createItemCategories = `-- name: CreateItemCategories :one
INSERT INTO schm_pos.item_categories (tenant_id,parent_id,code,name,description,created_at)
VALUES ($1,$2,$3,$4,$5,NOW()) RETURNING id, tenant_id, parent_id, code, name, description, created_at, updated_at, deleted_at, deleted_by
`

type CreateItemCategoriesParams struct {
	TenantID    pgtype.UUID
	ParentID    pgtype.UUID
	Code        string
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateItemCategories(ctx context.Context, arg CreateItemCategoriesParams) (SchmPosItemCategory, error) {
	row := q.db.QueryRow(ctx, createItemCategories,
		arg.TenantID,
		arg.ParentID,
		arg.Code,
		arg.Name,
		arg.Description,
	)
	var i SchmPosItemCategory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO schm_pos.outbox (aggregate_id, topic, key, payload, headers, attempts, created_at) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id, tenant_id, aggregate_id, topic, key, payload, headers, attempts, status, error_msg, retry_count, retry_at, created_at, updated_at, next_attempt_at
`

type CreateOutboxEventParams struct {
	AggregateID pgtype.UUID
	Topic       string
	Key         []byte
	Payload     []byte
	Headers     []byte
	Attempts    pgtype.Int4
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (SchmPosOutbox, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.AggregateID,
		arg.Topic,
		arg.Key,
		arg.Payload,
		arg.Headers,
		arg.Attempts,
		arg.CreatedAt,
	)
	var i SchmPosOutbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AggregateID,
		&i.Topic,
		&i.Key,
		&i.Payload,
		&i.Headers,
		&i.Attempts,
		&i.Status,
		&i.ErrorMsg,
		&i.RetryCount,
		&i.RetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextAttemptAt,
	)
	return i, err
}

const createUOM = `-- name: CreateUOM :one
INSERT INTO schm_pos.uoms (code, name, symbol, description, created_at) VALUES($1,$2,$3,$4,$5) RETURNING id, tenant_id, code, name, symbol, description, created_at, updated_at, deleted_at, deleted_by
`

type CreateUOMParams struct {
	Code        string
	Name        string
	Symbol      string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateUOM(ctx context.Context, arg CreateUOMParams) (SchmPosUom, error) {
	row := q.db.QueryRow(ctx, createUOM,
		arg.Code,
		arg.Name,
		arg.Symbol,
		arg.Description,
		arg.CreatedAt,
	)
	var i SchmPosUom
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const deleteItemCategories = `-- name: DeleteItemCategories :one
UPDATE schm_pos.item_categories
SET
    updated_at  = NOW(),
    deleted_at  = NOW(),
    deleted_by  = $1
WHERE id = $2 RETURNING id, tenant_id, parent_id, code, name, description, created_at, updated_at, deleted_at, deleted_by
`

type DeleteItemCategoriesParams struct {
	DeletedBy pgtype.UUID
	ID        pgtype.UUID
}

func (q *Queries) DeleteItemCategories(ctx context.Context, arg DeleteItemCategoriesParams) (SchmPosItemCategory, error) {
	row := q.db.QueryRow(ctx, deleteItemCategories, arg.DeletedBy, arg.ID)
	var i SchmPosItemCategory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const deleteUOM = `-- name: DeleteUOM :one
UPDATE schm_pos.uoms
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id=$1 RETURNING id, tenant_id, code, name, symbol, description, created_at, updated_at, deleted_at, deleted_by
`

func (q *Queries) DeleteUOM(ctx context.Context, id pgtype.UUID) (SchmPosUom, error) {
	row := q.db.QueryRow(ctx, deleteUOM, id)
	var i SchmPosUom
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const destroyOutbox = `-- name: DestroyOutbox :one
DELETE FROM schm_pos.outbox WHERE id=$1 RETURNING id, tenant_id, aggregate_id, topic, key, payload, headers, attempts, status, error_msg, retry_count, retry_at, created_at, updated_at, next_attempt_at
`

func (q *Queries) DestroyOutbox(ctx context.Context, id pgtype.UUID) (SchmPosOutbox, error) {
	row := q.db.QueryRow(ctx, destroyOutbox, id)
	var i SchmPosOutbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AggregateID,
		&i.Topic,
		&i.Key,
		&i.Payload,
		&i.Headers,
		&i.Attempts,
		&i.Status,
		&i.ErrorMsg,
		&i.RetryCount,
		&i.RetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextAttemptAt,
	)
	return i, err
}

const existsUOMByCode = `-- name: ExistsUOMByCode :one
SELECT EXISTS (
    SELECT 1
        FROM schm_pos.uoms
    WHERE
        code = $1
    AND 
        deleted_at IS NULL
)
`

func (q *Queries) ExistsUOMByCode(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRow(ctx, existsUOMByCode, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsUOMByID = `-- name: ExistsUOMByID :one
SELECT EXISTS (
    SELECT 1 
        FROM schm_pos.uoms
    WHERE 
        id = $1
    AND 
        deleted_at IS NULL
)
`

func (q *Queries) ExistsUOMByID(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, existsUOMByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsUOMBySymbol = `-- name: ExistsUOMBySymbol :one
SELECT EXISTS (
    SELECT 1
        FROM schm_pos.uoms
    WHERE
        symbol = $1
    AND 
        deleted_at IS NULL
)
`

func (q *Queries) ExistsUOMBySymbol(ctx context.Context, symbol string) (bool, error) {
	row := q.db.QueryRow(ctx, existsUOMBySymbol, symbol)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsUOMCodeExcludeID = `-- name: ExistsUOMCodeExcludeID :one
SELECT EXISTS (
    SELECT 1
    FROM schm_pos.uoms
    WHERE
        code = $1
        AND id <> $2
        AND deleted_at IS NULL
)
`

type ExistsUOMCodeExcludeIDParams struct {
	Code string
	ID   pgtype.UUID
}

func (q *Queries) ExistsUOMCodeExcludeID(ctx context.Context, arg ExistsUOMCodeExcludeIDParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsUOMCodeExcludeID, arg.Code, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getItemCategories = `-- name: GetItemCategories :one
SELECT 
    id,
    tenant_id,
    parent_id,
    code,
    name,
    description,
    created_at,
    updated_at
FROM schm_pos.item_categories
WHERE id=$1 AND deleted_at IS NULL
`

type GetItemCategoriesRow struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	ParentID    pgtype.UUID
	Code        string
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetItemCategories(ctx context.Context, id pgtype.UUID) (GetItemCategoriesRow, error) {
	row := q.db.QueryRow(ctx, getItemCategories, id)
	var i GetItemCategoriesRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutbox = `-- name: GetOutbox :one
SELECT 
    id,
    aggregate_id,
    topic,
    key,
    payload,
    headers,
    attempts,
    status,
    error_msg,
    retry_count,
    retry_at,
    created_at,
    updated_at,
    next_attempt_at
FROM schm_pos.outbox
WHERE
    id = $1
`

type GetOutboxRow struct {
	ID            pgtype.UUID
	AggregateID   pgtype.UUID
	Topic         string
	Key           []byte
	Payload       []byte
	Headers       []byte
	Attempts      pgtype.Int4
	Status        interface{}
	ErrorMsg      pgtype.Text
	RetryCount    pgtype.Int8
	RetryAt       pgtype.Timestamp
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	NextAttemptAt pgtype.Timestamptz
}

func (q *Queries) GetOutbox(ctx context.Context, id pgtype.UUID) (GetOutboxRow, error) {
	row := q.db.QueryRow(ctx, getOutbox, id)
	var i GetOutboxRow
	err := row.Scan(
		&i.ID,
		&i.AggregateID,
		&i.Topic,
		&i.Key,
		&i.Payload,
		&i.Headers,
		&i.Attempts,
		&i.Status,
		&i.ErrorMsg,
		&i.RetryCount,
		&i.RetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextAttemptAt,
	)
	return i, err
}

const getPendingOutbox = `-- name: GetPendingOutbox :many
SELECT
    id,
    aggregate_id,
    topic,
    key,
    payload,
    headers,
    attempts,
    status,
    error_msg,
    retry_count,
    retry_at,
    created_at,
    updated_at,
    next_attempt_at
FROM schm_pos.outbox
WHERE
    status = 'PENDING'
    AND (
        next_attempt_at IS NULL
        OR next_attempt_at <= NOW()
    )
ORDER BY created_at ASC
LIMIT $1
`

type GetPendingOutboxRow struct {
	ID            pgtype.UUID
	AggregateID   pgtype.UUID
	Topic         string
	Key           []byte
	Payload       []byte
	Headers       []byte
	Attempts      pgtype.Int4
	Status        interface{}
	ErrorMsg      pgtype.Text
	RetryCount    pgtype.Int8
	RetryAt       pgtype.Timestamp
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	NextAttemptAt pgtype.Timestamptz
}

func (q *Queries) GetPendingOutbox(ctx context.Context, limit int32) ([]GetPendingOutboxRow, error) {
	rows, err := q.db.Query(ctx, getPendingOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingOutboxRow
	for rows.Next() {
		var i GetPendingOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.Topic,
			&i.Key,
			&i.Payload,
			&i.Headers,
			&i.Attempts,
			&i.Status,
			&i.ErrorMsg,
			&i.RetryCount,
			&i.RetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUOM = `-- name: GetUOM :one
SELECT 
    code,
    name,
    symbol,
    description,
    created_at,
    updated_at
FROM schm_pos.uoms
WHERE id = $1 AND deleted_at IS NULL
`

type GetUOMRow struct {
	Code        string
	Name        string
	Symbol      string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetUOM(ctx context.Context, id pgtype.UUID) (GetUOMRow, error) {
	row := q.db.QueryRow(ctx, getUOM, id)
	var i GetUOMRow
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listsItemCategories = `-- name: ListsItemCategories :many
SELECT 
    id,
    tenant_id,
    parent_id,
    code,
    name,
    description,
    created_at,
    updated_at
FROM schm_pos.item_categories 
WHERE 
    deleted_at IS NULL
    AND (
        $1::uuid IS NULL
        OR tenant_id = $1::uuid
    )
ORDER BY name
`

type ListsItemCategoriesRow struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	ParentID    pgtype.UUID
	Code        string
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListsItemCategories(ctx context.Context, tenantID pgtype.UUID) ([]ListsItemCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listsItemCategories, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListsItemCategoriesRow
	for rows.Next() {
		var i ListsItemCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ParentID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listsItemCategoriesTree = `-- name: ListsItemCategoriesTree :many
WITH RECURSIVE category_tree AS (
    SELECT
        ic.id,
        ic.tenant_id,
        ic.parent_id,
        ic.code,
        ic.name,
        ic.description,
        ic.created_at,
        ic.updated_at,
        ic.deleted_at,
        0::int AS level,
        ARRAY[id::text] AS path
    FROM schm_pos.item_categories as ic
    WHERE
        ic.parent_id IS NULL
        AND ic.tenant_id = $1
        AND ic.deleted_at IS NULL

    UNION ALL

    SELECT
        c.id,
        c.parent_id,
        c.code,
        c.name,
        c.description,
        c.created_at,
        c.updated_at,
        c.deleted_at,
        ct.level + 1,
        ct.path || c.id::text
    FROM schm_pos.item_categories c
    INNER JOIN category_tree ct
        ON c.parent_id = ct.id
    WHERE
        c.deleted_at IS NULL
)
SELECT id, tenant_id, parent_id, code, name, description, created_at, updated_at, deleted_at, level, path
FROM category_tree
ORDER BY path
`

type ListsItemCategoriesTreeRow struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	ParentID    pgtype.UUID
	Code        string
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	Level       int32
	Path        interface{}
}

func (q *Queries) ListsItemCategoriesTree(ctx context.Context, tenantID pgtype.UUID) ([]ListsItemCategoriesTreeRow, error) {
	rows, err := q.db.Query(ctx, listsItemCategoriesTree, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListsItemCategoriesTreeRow
	for rows.Next() {
		var i ListsItemCategoriesTreeRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ParentID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Level,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listsUOMS = `-- name: ListsUOMS :many
SELECT 
    code,
    name,
    symbol,
    description,
    created_at,
    updated_at
FROM schm_pos.uoms WHERE deleted_at IS NULL
`

type ListsUOMSRow struct {
	Code        string
	Name        string
	Symbol      string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListsUOMS(ctx context.Context) ([]ListsUOMSRow, error) {
	rows, err := q.db.Query(ctx, listsUOMS)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListsUOMSRow
	for rows.Next() {
		var i ListsUOMSRow
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Symbol,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const outboxLists = `-- name: OutboxLists :many
SELECT 
    id,
    aggregate_id,
    topic,
    key,
    payload,
    headers,
    attempts,
    status,
    error_msg,
    retry_count,
    retry_at,
    created_at,
    updated_at,
    next_attempt_at
FROM schm_pos.outbox
`

type OutboxListsRow struct {
	ID            pgtype.UUID
	AggregateID   pgtype.UUID
	Topic         string
	Key           []byte
	Payload       []byte
	Headers       []byte
	Attempts      pgtype.Int4
	Status        interface{}
	ErrorMsg      pgtype.Text
	RetryCount    pgtype.Int8
	RetryAt       pgtype.Timestamp
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	NextAttemptAt pgtype.Timestamptz
}

func (q *Queries) OutboxLists(ctx context.Context) ([]OutboxListsRow, error) {
	rows, err := q.db.Query(ctx, outboxLists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxListsRow
	for rows.Next() {
		var i OutboxListsRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.Topic,
			&i.Key,
			&i.Payload,
			&i.Headers,
			&i.Attempts,
			&i.Status,
			&i.ErrorMsg,
			&i.RetryCount,
			&i.RetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreItemCategories = `-- name: RestoreItemCategories :one
UPDATE schm_pos.item_categories
SET
    updated_at  = NOW(),
    deleted_at  = NULL
WHERE id = $1 RETURNING id, tenant_id, parent_id, code, name, description, created_at, updated_at, deleted_at, deleted_by
`

func (q *Queries) RestoreItemCategories(ctx context.Context, id pgtype.UUID) (SchmPosItemCategory, error) {
	row := q.db.QueryRow(ctx, restoreItemCategories, id)
	var i SchmPosItemCategory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const restoreUOM = `-- name: RestoreUOM :one
UPDATE schm_pos.uoms
SET
    deleted_at = NULL,
    updated_at = NOW()
WHERE id=$1 RETURNING id, tenant_id, code, name, symbol, description, created_at, updated_at, deleted_at, deleted_by
`

func (q *Queries) RestoreUOM(ctx context.Context, id pgtype.UUID) (SchmPosUom, error) {
	row := q.db.QueryRow(ctx, restoreUOM, id)
	var i SchmPosUom
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const updateItemCategories = `-- name: UpdateItemCategories :one
UPDATE schm_pos.item_categories
SET
    tenant_id   = COALESCE($1, tenant_id),
    parent_id   = COALESCE($2, parent_id),
    code        = COALESCE($3, code),
    name        = COALESCE($4, name),
    description = COALESCE($5, description),
    updated_at  = NOW()
WHERE id = $6 RETURNING id, tenant_id, parent_id, code, name, description, created_at, updated_at, deleted_at, deleted_by
`

type UpdateItemCategoriesParams struct {
	TenantID    pgtype.UUID
	ParentID    pgtype.UUID
	Code        pgtype.Text
	Name        pgtype.Text
	Description pgtype.Text
	ID          pgtype.UUID
}

func (q *Queries) UpdateItemCategories(ctx context.Context, arg UpdateItemCategoriesParams) (SchmPosItemCategory, error) {
	row := q.db.QueryRow(ctx, updateItemCategories,
		arg.TenantID,
		arg.ParentID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.ID,
	)
	var i SchmPosItemCategory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const updateOutbox = `-- name: UpdateOutbox :one
UPDATE schm_pos.outbox
SET 
    status          = COALESCE($1, status),
    attempts        = COALESCE($2, attempts),
    retry_count     = COALESCE($3, retry_count),
    error_msg       = COALESCE($4, error_msg),
    retry_at        = COALESCE($5, retry_at),
    next_attempt_at = COALESCE($6, next_attempt_at),
    updated_at      = NOW()
WHERE id = $7
RETURNING id, tenant_id, aggregate_id, topic, key, payload, headers, attempts, status, error_msg, retry_count, retry_at, created_at, updated_at, next_attempt_at
`

type UpdateOutboxParams struct {
	Status        interface{}
	Attempts      pgtype.Int4
	RetryCount    pgtype.Int8
	ErrorMsg      pgtype.Text
	RetryAt       pgtype.Timestamp
	NextAttemptAt pgtype.Timestamptz
	ID            pgtype.UUID
}

func (q *Queries) UpdateOutbox(ctx context.Context, arg UpdateOutboxParams) (SchmPosOutbox, error) {
	row := q.db.QueryRow(ctx, updateOutbox,
		arg.Status,
		arg.Attempts,
		arg.RetryCount,
		arg.ErrorMsg,
		arg.RetryAt,
		arg.NextAttemptAt,
		arg.ID,
	)
	var i SchmPosOutbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AggregateID,
		&i.Topic,
		&i.Key,
		&i.Payload,
		&i.Headers,
		&i.Attempts,
		&i.Status,
		&i.ErrorMsg,
		&i.RetryCount,
		&i.RetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextAttemptAt,
	)
	return i, err
}

const updatedUOM = `-- name: UpdatedUOM :one
UPDATE schm_pos.uoms
SET
    code        = COALESCE($1, code),
    name        = COALESCE($2, name),
    symbol      = COALESCE($3, symbol),
    description = COALESCE($4, description),
    updated_at  = NOW()
WHERE id = $5
RETURNING id, tenant_id, code, name, symbol, description, created_at, updated_at, deleted_at, deleted_by
`

type UpdatedUOMParams struct {
	Code        pgtype.Text
	Name        pgtype.Text
	Symbol      pgtype.Text
	Description pgtype.Text
	ID          pgtype.UUID
}

func (q *Queries) UpdatedUOM(ctx context.Context, arg UpdatedUOMParams) (SchmPosUom, error) {
	row := q.db.QueryRow(ctx, updatedUOM,
		arg.Code,
		arg.Name,
		arg.Symbol,
		arg.Description,
		arg.ID,
	)
	var i SchmPosUom
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
