// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Author struct {
	ID    int32
	Name  string
	Email string
	Bio   sql.NullString
}

type Book struct {
	ID            int32
	Title         string
	Isbn          string
	PublishedDate sql.NullTime
	AuthorID      sql.NullInt32
}

type Review struct {
	ID        int32
	BookID    sql.NullInt32
	UserID    int32
	Rating    sql.NullInt32
	Comment   sql.NullString
	CreatedAt sql.NullTime
}
