// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: schema.sql

package db

import (
	"context"
	"database/sql"
)

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (name, email, bio)
VALUES ($1, $2, $3)
RETURNING id, name, email, bio
`

type CreateAuthorParams struct {
	Name  string
	Email string
	Bio   sql.NullString
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error) {
	row := q.db.QueryRowContext(ctx, createAuthor, arg.Name, arg.Email, arg.Bio)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Bio,
	)
	return i, err
}

const createBook = `-- name: CreateBook :one
INSERT INTO books (title, isbn, published_date, author_id)
VALUES ($1, $2, $3, $4)
RETURNING id, title, isbn, published_date, author_id
`

type CreateBookParams struct {
	Title         string
	Isbn          string
	PublishedDate sql.NullTime
	AuthorID      sql.NullInt32
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook,
		arg.Title,
		arg.Isbn,
		arg.PublishedDate,
		arg.AuthorID,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Isbn,
		&i.PublishedDate,
		&i.AuthorID,
	)
	return i, err
}

const getAuthor = `-- name: GetAuthor :one
SELECT id, name, email, bio FROM authors WHERE id = $1
`

// Queries
func (q *Queries) GetAuthor(ctx context.Context, id int32) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthor, id)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Bio,
	)
	return i, err
}

const getAuthorBooks = `-- name: GetAuthorBooks :many
SELECT id, title, isbn, published_date, author_id FROM books WHERE author_id = $1 ORDER BY published_date
`

func (q *Queries) GetAuthorBooks(ctx context.Context, authorID sql.NullInt32) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, getAuthorBooks, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Isbn,
			&i.PublishedDate,
			&i.AuthorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBook = `-- name: GetBook :one
SELECT id, title, isbn, published_date, author_id FROM books WHERE id = $1
`

func (q *Queries) GetBook(ctx context.Context, id int32) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Isbn,
		&i.PublishedDate,
		&i.AuthorID,
	)
	return i, err
}

const getBookReviews = `-- name: GetBookReviews :many
SELECT id, book_id, user_id, rating, comment, created_at FROM reviews WHERE book_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetBookReviews(ctx context.Context, bookID sql.NullInt32) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, getBookReviews, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.UserID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, name, email, bio FROM authors ORDER BY name
`

func (q *Queries) ListAuthors(ctx context.Context) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooks = `-- name: ListBooks :many
SELECT b.id, b.title, b.isbn, b.published_date, b.author_id, a.name as author_name 
FROM books b
JOIN authors a ON b.author_id = a.id
ORDER BY b.published_date DESC
`

type ListBooksRow struct {
	ID            int32
	Title         string
	Isbn          string
	PublishedDate sql.NullTime
	AuthorID      sql.NullInt32
	AuthorName    string
}

func (q *Queries) ListBooks(ctx context.Context) ([]ListBooksRow, error) {
	rows, err := q.db.QueryContext(ctx, listBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBooksRow
	for rows.Next() {
		var i ListBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Isbn,
			&i.PublishedDate,
			&i.AuthorID,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
